server:
  port: 8080

spring:
  rabbitmq:
    host: rabbitmq的ip
    port: 5672
    username: 账号
    password: 密码
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 3000

  elasticsearch:
    uris: xqyprod.huayu.asia:9200
    password: c=cqm5pq-Fhq_mNVCexY
    username: elastic

  mail:
    host: smtp.163.com
    username:
    password: 密码
    default-encoding: UTF-8
    protocol: smtp
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
          ssl:
            enable: true
          starttls:
            enable: true
            required: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

search:
  mode: elasticsearch
# 微服务形式  Feign调用file模块
upload:
  mode: minio
  oss:
    url: http://Bucket域名/
    endpoint: OSS配置endpoint
    accessKeyId: OSS配置accessKeyId
    accessKeySecret: OSS配置accessKeySecret
    bucketName: OSS配置bucketName
  minio:
    url: http://huayu.asia:9000
    endpoint: http://minio的ip:9000
    accesskey: 用户名
    secretKey: 密码
    bucketName: 桶的名称

website:
  url: https://prod.huayu.asia

qq:
  app-id: QQ APPID
  check-token-url: https://graph.qq.com/oauth2.0/me?access_token={access_token}
  user-info-url: https://graph.qq.com/user/get_user_info?openid={openid}&access_token={access_token}&oauth_consumer_key={oauth_consumer_key}