version: '3.7'

services:
  blog:
    hostname: blog
    image: swr.cn-east-3.myhuaweicloud.com/huayu/sofa-server-blog:latest
    # volumes:
    #   - /opt/server_blog-0.0.1-SNAPSHOT.jar:/blog.jar
    labels:
      "type": "1"
    networks:
      - ali
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  file:
    hostname: file
    image: swr.cn-east-3.myhuaweicloud.com/huayu/sofa-server-file:latest
    labels:
      "type": "1"
    networks:
      - ali
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  admin:
    hostname: admin
    image: swr.cn-east-3.myhuaweicloud.com/huayu/sofa-server-admin:latest
    labels:
      "type": "1"
    networks:
      - ali
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
networks:
  ali:
    external: true
    name: huayu